### ISSUE TITLE
How to convert gif with it?

### ISSUE THREAD

**Issue by tonyshkurenko** [paulasiimwe/Android-ImageMagick#11]
I tried to create gif from frames with this code, but it doesn't work. I created an question in the StackOverflow (http://stackoverflow.com/questions/34086141/imagemagick-android-convert-jpegs-to-gif), but no one answered.
```
final List<MagickImage> frames = new ArrayList<>();

for (final String bitmapPath : bitmapPaths) {
  final MagickImage image = new MagickImage(new ImageInfo(bitmapPath));
  final QuantizeInfo quantizeInfo = new QuantizeInfo();
  quantizeInfo.setNumberColors(256);
  quantizeInfo.setTreeDepth(4); // 8 is max
  image.quantizeImage(quantizeInfo);
  frames.add(image);
}

Timber.v("Frames: %s", frames.toString()); // first test log
final MagickImage[] images = frames.toArray(new MagickImage[frames.size()]);
final MagickImage finalGif = new MagickImage(images);
finalGif.setDelay(FRAME_FREQUENCY / 10);
finalGif.setImageFormat("gif");
finalGif.setIterations(1000); // temp, want to make infinity loops
Timber.d("Is animated: %b", finalGif.isAnimatedImage());
Timber.d("Has frames: %b, number of frames: %d", finalGif.hasFrames(),
    finalGif.getNumFrames());
final ImageInfo resultInfo = new ImageInfo(path);
Timber.d("Result path: %s", resultInfo.getFileName());
resultInfo.setMagick("gif");
//finalGif.writeImage(resultInfo); // it doesn't write to the file
final byte[] img = finalGif.imageToBlob(resultInfo);
Timber.d("Image bytes count: %d", img.length);

FileUtils.store(img, path);
```

**Comment by paulasiimwe** [comment]
Hi,
Unfortunately I'm unable to help you here.
Im no expert in ImageMagick, i simply used my knowledge of Android NDK to reorder and rearrange existing repos to build this one and it's related .so files.
I only needed it for a College project at the time.
You might have better luck on the imagemagick.org forums...
Thanks.

**Comment by tonyshkurenko** [comment]
Thanks! I will post link here, if I find the answer

**Comment by paulasiimwe** [comment]
Here is the link to the Community, register and ask there:
http://www.imagemagick.org/discourse-server/

**Comment by iAlex97** [comment]
Hello,
I'm trying to do the same thing. Did you had any luck to get it to work?

**Comment by tonyshkurenko** [comment]
No :)

**Comment by iAlex97** [comment]
For me, when I'm using `finalGif.writeImage(resultInfo);` it seems to write the gif into the first frame file and crash without any stacktrace.

**Comment by tonyshkurenko** [comment]
I used another solution, I don't know

**Comment by iAlex97** [comment]
Can you please share ti with me?

**Comment by tonyshkurenko** [comment]
It's here: http://stackoverflow.com/questions/33941767/converting-jpegs-to-gifs-is-too-long

**Comment by iAlex97** [comment]
Ok, thank you very much!

**Comment by rajashekarvys** [comment]
I'm trying to do the same thing, did you find any solution

**Comment by tonyshkurenko** [comment]
@rajashekarvys no, follow answers in the top
