### ISSUE TITLE
Oh my God

### ISSUE THREAD

**Issue by 271845221** [paulasiimwe/Android-ImageMagick#14]
The .so files has dozens of MB. As bellow:
![d9c21eab-bb07-4687-86ea-4af25a7d8030](https://cloud.githubusercontent.com/assets/11680997/15502712/477f25a4-21e8-11e6-80d0-54965168e0d1.png)

I just want to do that，as follows：
![image](https://cloud.githubusercontent.com/assets/11680997/15502792/ad7c45bc-21e8-11e6-9929-c359d81e6f4b.png)

How can I do？

**Comment by paulasiimwe** [comment]
You are using all .so files for all CPU ABIs, your device only uses one CPU ABI, most likely armeabi-v7a.

**Comment by 271845221** [comment]
Thank you for your generous help. If I just want to get the quality of image in Android platform, can you give me some suggestions？
