### ISSUE TITLE
How to run/execute commands like convert image.jpg image.png 

### ISSUE THREAD

**Issue by rajscet** [paulasiimwe/Android-ImageMagick#15]
I want to edit images using command line in android. is there any way to edit images directly using command line

**Comment by paulasiimwe** [comment]
You cannot do that here as the .so files provided are meant to be used and accessed through APKs.
However these  threads here seems to hint at solving your problem.

http://www.xda-developers.com/transform-your-android-device-into-a-powerful-linux-machine-with-zshaolin/

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi-kN3urvjMAhVGbRQKHRPtBwEQFggcMAA&url=http%3A%2F%2Fforum.xda-developers.com%2Fandroid%2Fthemes%2Fimagemagick-android-t2852481&usg=AFQjCNFu_ThUdBJFGGtDioo2yyPgp5wW2g&sig2=ivw9BHjoBpnGasDH0Eycqg


You'd probably need to store the full ImageMagick source code/compiled libs or any other Image Library's source code for Linux onto your phone and access the library via the terminal, of course the library itself has to support a command line interface.

**Comment by rajscet** [comment]
you right. I am new for such type of library. can you build such type of app for android? if you can do , it will be great achievements for you. Because command line works fast with less complexity of code. People can build good apps as ImageMagic provides lots of functions. I am able to do same thing for FFMPEG using this link:https://github.com/WritingMinds/ffmpeg-android-java

I want more image processing with ImageMagic and FFMPEG to build beautiful app. without command line in image magic its is tough to manage code.
