### ISSUE TITLE
Running into a fatal signal 11 error on first install

### ISSUE THREAD

**Issue by kamcknig** [paulasiimwe/Android-ImageMagick#4]
Hi! Thanks so much for your work on this!

I'm trying to get it up and running, but it doesn't seem to be working for me.

1. I've copied over the libs folder so my libs folder contains armeabi and armeabi-v7a.
2. See 1, I deleted the x86 and mips
3. I copied over the Magick and fakeawt folders to my source folder
4. I've created a jni folder in the same parent folder as my source folder
5. I added an Application.mk file that contains the text "APP_ABI := armeabi armeabi-v7a" and "APP_PLATFORM := android-14" (without the quotes and on two lines)
6. I have created my main activity and all it does is the first step of creating an MagickImage object using this code

 String s = Environment.getExternalStorageDirectory().getAbsolutePath() + "/Download/IMG_test.jpg";
        Log.d("TEST", s);

        try {
            ImageInfo imageInfo = new ImageInfo(s);
            final MagickImage img = new MagickImage(imageInfo);
        }
        catch (MagickApiException e) {
            e.printStackTrace();
        }
        catch (MagickException e) {
            e.printStackTrace();
        }

I get my log message with the string that pionts at the correct file. ImageInfo seems to be created just fine (no errors anyway if i comment out the next line). But when creating the MagickImage object I get the following error "06-15 21:49:28.334  31431-31431/com.example.ImageMagickTest A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 31431 (ImageMagickTest)"

I also get a few log statemnts from dalvikvm and Magick before that

06-15 21:49:28.334  31431-31431/com.example.ImageMagickTest D/dalvikvm﹕ Trying to load lib /data/app-lib/com.example.ImageMagickTest-1/libimagemagick.so 0x425b44f8
06-15 21:49:28.334  31431-31431/com.example.ImageMagickTest D/dalvikvm﹕ Added shared lib /data/app-lib/com.example.ImageMagickTest-1/libimagemagick.so 0x425b44f8
06-15 21:49:28.334  31431-31431/com.example.ImageMagickTest D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.example.ImageMagickTest-1/libimagemagick.so 0x425b44f8, skipping init
06-15 21:49:28.334  31431-31431/com.example.ImageMagickTest V/Magick﹕ Attempting to read from file /storage/emulated/0/Download/IMG_test.jpg

I don't have any clue how to fix this. And the jni folder confuses me to as I'm not sure what that's really even used for (looking in yours and seeing all that stuff)

**Comment by aurk** [comment]
Hi paulasiimwe,

I'm getting same issue. Can you please help me to resolve this issue.

I just added 
       static {
	    System.loadLibrary("imagemagick");
	}
piece of code but still getting same issue

**Comment by paulasiimwe** [comment]
I also experience this alot.
Im yet to find out the cause.
Any help is appreciated.

**Comment by pasella** [comment]
Hie geeks,

I'm a noob in android and I'm facing the same problem as you for a couple of days so far.

Before going further on yhat pb I want to thank Paulassiiwe for the job  he is doing on that project. 

//My context
I'm on windows 7 64b Eclipse Luna; android ndk-r10; cygwin; npp++; st3

//OK let's play around that issue
The pb seems to lie around the readImage(imageinfo) that is called by MagickInfo(i) on TestedNdkActivity. That pb throw a MagickException. And if you look at our Logcat it tells us Tag = libc

That function is the first native fonction riched by onCreate(bundle) from TestedndkActivity.


//Accessibility to *.so
Now if we look into /android-lib-magick/libs/armeabi/ we see the two *.so available in the project .
libandroid-magick.so
libndk1.so
see under /android-lib-magick/libs/armeabi/

Now if i have a look deep into the libandroid-magick.so I find a string named  Java_magick_MagickImage_readImage that means for me that the fonction readImage has access to the libandroid-magick.so

Now if I look into /android-lib-magick/libs/armeabi/libndk1.so, I won't find any readImage nor Java_magick_.

I deduce TestedNdkActivity has no access to libandroid-magick.so 

Is there an issue around the build path??
Aniway i copied libndk1.so the /android-lib-magick/libs/armeabi/ into the /android-lib-magick/obj/local/armeabi/
 I clean the projet and re test the apli but the pb is still there

//Fonction signature
 Now if I have a look at http://www.imagemagick.org/api/constitute.php#ReadImage, as mentionned in the code, we notice that the signature of readImage(param1) doesn't look like what it is expected by the libc
  Image *ReadImage(const ImageInfo *image_info,ExceptionInfo *exception)
  We have two params there.

Is that a hint for you all?

I think that piste is the most serious so i'll play around from now and let you know in a while.

Sorry for my broken english, I'm french.
Regards

**Comment by pasella** [comment]
Hie guies,
As promised i come back.

Our pb is on the path which is given to new ImageInfo(path-to-the-file)
Just make sure the path is riching a file present into the device yoou are pointing to.

That's pretty much in coherence with what is writen here http://www.imagemagick.org/api/constitute.php#ReadImage
"ReadImage() reads an image or image sequence from a file or file handle. The method returns a NULL if there is a memory shortage or if the image cannot be read. On failure, a NULL image is returned and exception describes the reason for the failure."

To verify which file you are targeting on your physical device you can use adb in a command line.
http://developer.android.com/tools/help/adb.html
Then using shell you can surf in the file system of your physical device and play arround to identify a real file in there.
Now type this full path in the                new ImageInfo(full-real-path-to-present-file-on-your-device); in TesteNdkActivity.java

Should work, ;-) ...nevertheless you won't get A/libc(1425): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 1425 (teste.ndk)

So I hope it'll help.
Keep going on this project.
Enjoy

Olivier

**Comment by pasella** [comment]
Hie guies,

one more ting to notice about the path which is required by ImageInfo i = new ImageInfo(fullFileName);

we must avoid to hardcode it.
I've a problem after having shuting down both my pc and my smartphone. When I re start all  my staff and try to use the aplication it rased up a so well know:
 Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 1425 (teste.ndk)!!

According to this http://developer.android.com/reference/android/os/Environment.html
I modify my code (se after), and then it works fine even after shutting down and restart my staff.

//The modification made in TesteNdkActivity.java

// instead of harcoding like this "/sdcard/DCIM/Camera/image_in.jpg"
File path = Environment.getExternalStoragePublicDirectory(
                  Environment.DIRECTORY_DCIM);
String myImage = "/Camera/image-in.jpg";
String fullFileName = path.toString() + myImage;
		
 ImageInfo i = new ImageInfo(fullFileName);

...

Enjoy.
Oliver

**Comment by aurk** [comment]
Hi,

I found that imagemagick response is very slow. It take sometime around 20 to 25 seconds... It's taking too much time for processing.... Is there any other library that take some short amount of time to process?

**Comment by pasella** [comment]
Hi auw,
I don't know because I didn't check.Nevertheless I think that modifying images cost a lot regarding cpu depending on wath job you are doing on an image.Especially on big one.

Of course the device (physical)you are using is important too.

I'am not familiar to use tools that evalute an aplication yet. But you probably have to look at that point to figure out where the time is spent.
Did you try to do the same job on the image,using ImageMagick CLI (Commande Line Interface) and compare the time it takes to the one on your device through your android application.

Good luck.
Olivier

**Comment by paulasiimwe** [comment]
I just want to say, thank you Pasella

**Comment by paulasiimwe** [comment]
@aurk you could try DevIL,aviary,openCV sorry for the late response

**Comment by bu2zhouzhu** [comment]
AndroidMagickActivity.java, line 48. Replace path "/sdcard/1.jpg" to a path of an image exist in your phone.
