### ISSUE TITLE
Crash with exported apk

### ISSUE THREAD

**Issue by harunurhan** [paulasiimwe/Android-ImageMagick#7]
Hi, ImageMagick works great in my application while debugging. However when I export my app in order to publish and test, it crashes. I am sure that it is due to ImageMagick because my app crashes only when I try to use ImageMagick related functions.

I think I could not export source completely, some libs (ImageMagick) skipped obviously while exporting. How can I produce a complete export with all external libs in it.

**Comment by paulasiimwe** [comment]
Please add these flags in your proguard file
-keep class magick.** { *; }
-keep class fakeawt.** { *; }

you can ignore my comment above.
